#!/bin/bash

sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q "
CREATE AVAILABILITY GROUP [ag_demo]
FOR DATABASE [master]
REPLICA ON 
  'mssql_0' WITH (ENDPOINT_URL = 'TCP://mssql_0:5022', AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = AUTOMATIC),
  'mssql_1' WITH (ENDPOINT_URL = 'TCP://mssql_1:5022', AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = AUTOMATIC);
"
